{
 "title": "Napelem",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Aktuális Betáp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "device_mode",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kimenő teljesítmény",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_apparent_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Havi fogyasztás",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_active_power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Napelem havi termelés",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "query": "SELECT integral(\"solar_power\")  / 3600000 FROM (SELECT \"pv_input_voltage\" * \"pv_input_current\" AS solar_power FROM \"operational_status\") WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "solar_power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akku havi töltés",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "query": "SELECT integral(\"charging_power\")  / 3600000 FROM (SELECT \"battery_voltage\" * \"battery_charging_current\" AS charging_power FROM \"operational_status\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "solar_power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akku havi használat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "query": "SELECT integral(\"discharge_power\")  / 3600000 FROM (SELECT \"battery_voltage\" * \"battery_discharge_current\" AS discharge_power FROM \"operational_status\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "solar_power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kimenő feszültség",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mai fogyasztás",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_active_power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Napelem mai termelés",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "query": "SELECT integral(\"solar_power\")  / 3600000 FROM (SELECT \"pv_input_voltage\" * \"pv_input_current\" AS solar_power FROM \"operational_status\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "solar_power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akku mai töltés",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "query": "SELECT integral(\"charging_power\")  / 3600000 FROM (SELECT \"battery_voltage\" * \"battery_charging_current\" AS charging_power FROM \"operational_status\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "solar_power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akku mai használat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "query": "SELECT integral(\"discharge_power\")  / 3600000 FROM (SELECT \"battery_voltage\" * \"battery_discharge_current\" AS discharge_power FROM \"operational_status\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" },
       { "params": [ "solar_power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kimenő frekvencia",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hálózati Betáp (MVM Next)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "hálózati feszültség",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "grid_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "hálózati frekvencia",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "grid_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kimenő Teljesítmény",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "hasznos teljesítmény (W)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_active_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "összes teljesítmény (VA)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "ac_output_apparent_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "kapacitás",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "output_load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Napelemek",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "panelfeszültség",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "pv_input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "áramerősség",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "query": "SELECT mean(\"pv_input_current\") FROM \"operational_status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MPPT teljesítmény",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "query": "SELECT mean(\"pv_input_current\")  * mean(\"pv_input_voltage\")\n FROM \"operational_status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n\n",
     "select": [
      [
       { "params": [ "pv_input_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Hibajelzések",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "alias": "*",
     "measurement": "warning_status",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energiaforrás",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "EF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_mode",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akkumulátor kapacitás",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "töltöttség",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "battery_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hőháztartás",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "hűtőborda hőmérséklet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "heat_sink_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akkumulátor forgalom",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "töltőáram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "battery_charging_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "kisütőáram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "battery_discharge_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "telepfeszültség",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "operational_status",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}